language: python
python:
  - '2.7'
  - '3.4'
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  global:
  - DEBUG=False
  - SECRET=SuperSecret
  - SQLALCHEMY_DATABASE_URI=sqlite://app.sqlite
  - TWILIO_ACCOUNT_SID=AC2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - TWILIO_AUTH_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - TWILIO_NUMBER=+15551230987
script:
  - coverage run --source=employee_directory_flask manage.py test
after_script:
  - coverage report
